title: Servicestatus – Unikino GEGENLICHT
buildFuture: true
languageCode: en
defaultContentLanguage: en
baseURL: https://status.gegenlicht.net
enableGitInfo: true

params:
  categories:
    - name: Uncategorized
      untitled: true
    - name: E-Mail Services

  systems:
    - name: website
      displayName: Website
      category: Uncategorized
      link: https://gegenlicht.net
      histogram: true

    - name: website-analytics
      displayName: Plausible Analytics
      category: Uncategorized
      histogram: true
      link: https://plausible.gegenlicht.net

    - name: sso
      displayName: Single-Sign On
      category: Uncategorized
      histogram: true
      link: https://accounts.gegenlicht.net

    - name: knowledge-base
      displayName: Knowledge Base
      category: Uncategorized
      histogram: true
      link: https://wiki.gegenlicht.net

    - name: appointment-planner
      displayName: Appointment Planner
      category: Uncategorized
      histogram: true
      link: https://terminplaner.gegenlicht.net

    - name: survey-tools
      displayName: Surveys and Forms
      category: Uncategorized
      histogram: true
      link: https://terminplaner.gegenlicht.net

    - name: email-groupware
      displayName: Groupware
      category: E-Mail Services
      histogram: true
      link: https://portal.gegenlicht.net

    - name: list-manager
      displayName: List Management
      category: E-Mail Services
      histogram: true
      link: https://lists.gegenlicht.net

    - name: imap
      displayName: IMAP
      category: E-Mail Services
      histogram: true

    - name: imap-tls
      displayName: IMAP (TLS)
      category: E-Mail Services
      histogram: true

    - name: smtp
      displayName: SMTP
      category: E-Mail Services
      histogram: true

    - name: smtp-tls
      displayName: SMTP (TLS)
      category: E-Mail Services
      histogram: true

    - name: smtp-submisson
      displayName: SMTP (Submission)
      category: E-Mail Services
      histogram: true

  dateFormat: "January 2, 2006 at 3:04 PM"
  shortDateFormat: "15:04 — Jan 2"
  useRelativeTime: true
  skipSeconds: false
  enableLastMod: true
  useLargeHeaderDesign: true
  incidentHistoryFormat: "yearly"
  disableIncidentHistory: false
  useLogo: true
  logo: logo.png
  disableComplexCalculations: false
  incidentPostsPerPage: 10
  brand: "#000000"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"
  alwaysKeepBrandColor: true
  headerTextColor: white
  enableUptimeHistogram: true
  googleAnalytics: UA-00000000-1

theme: cstate

preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
